services:
  postgres:
    image: postgres:16.1
    container_name: all-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - ./init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER" ]
      timeout: 5s
      interval: 5s
      retries: 10

volumes:
  postgres-data: