services:
  stats-server:
    build: ./stats-server/stats-service
    container_name: stats-server
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
    depends_on:
      stats-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://stats-server:9090/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5432:5432"
    volumes:
      - stats-db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=statsdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build: ./ewm
    container_name: ewm-service
    ports:
      - "8080:8080"
    environment:
      - STATS_SERVICE_URL=http://stats-server:9090
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
    depends_on:
      ewm-db:
        condition: service_healthy
      stats-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://ewm-service:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "5433:5432"
    volumes:
      - ewm-db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ewmdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      timeout: 5s
      interval: 5s
      retries: 10

volumes:
  stats-db-data:
  ewm-db-data: