server:
  port: 0 # Порт, на котором будет работать сервис (0-выбирается случайным образом)

grpc:
  server:
    port: 0

spring:
  kafka:
    bootstrap-servers: localhost:9092

kafka:
  producer-properties:
    bootstrap.servers: localhost:9092
    key.serializer: org.apache.kafka.common.serialization.LongSerializer
    value.serializer: ru.practicum.GeneralAvroSerializer
    # Настройки батчинга
    batch.size: 16384                    # Максимальный объем батча в байтах (16KB)
    linger.ms: 100                       # Максимальное время ожидания в ms
    buffer.memory: 33554432              # Общий объем буфера в байтах (32MB)
    max.request.size: 1048576            # Максимальный размер запроса в байтах (1MB)
    compression.type: none               # Тип сжатия (none, gzip, snappy, lz4, zstd)

  topics:
    USER_ACTION: stats.user-actions.v1
    EVENT_SIMILARITY: stats.events-similarity.v1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,configprops

logging:
  level:
    ru.practicum: DEBUG