server:
  port: 8080 # Порт, на котором будет работать сервис

spring:
  cloud:
    gateway:
      # Глобальные настройки Retry (новый формат)
      default-filters:
        - name: Retry
          args:
            retries: 3
            series: SERVER_ERROR, NOT_FOUND
            methods: GET,HEAD
            exceptions: java.io.IOException, java.util.concurrent.TimeoutException
            backoff:
              firstBackoff: 10ms
              maxBackoff: 100ms
              factor: 2
              basedOnPreviousValue: false

      # Настройки маршрутов
      server:
        webflux:
          routes:
            - id: user_service_route
              uri: lb://user-service
              predicates:
                - Path=/admin/users/**

            - id: comment_service_route
              uri: lb://comment-service
              predicates:
                - Path=/admin/comments/**, /users/{userId}/comments/**, /events/comments, /events/{eventId}/comments

            - id: request_service_route
              uri: lb://request-service
              predicates:
                - Path=/admin/requests/**, /users/{userId}/requests/**, /users/{userId}/events/{eventId}/requests/**

            - id: event_service_route
              uri: lb://event-service
              predicates:
                - Path=/admin/events/**, /events/**, /users/{userId}/events/**, /admin/categories/**, /categories/**, /admin/compilations/**, /compilations/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics,configprops
  endpoint:
    gateway:
      access: read_only
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.boot.context.config: INFO

# Для отладки
debug: true