server:
  port: 8080

spring:
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        jdbc.time_zone: UTC
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql.init.mode: always
  datasource:
    url: jdbc:postgresql://localhost:5433/ewmdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345

logging:
  level:
    org.springframework:
      orm.jpa: INFO
      transaction: INFO
      transaction.interceptor: TRACE
      orm.jpa.JpaTransactionManager: DEBUG

stats:
  service:
    url: http://localhost:9090
    name: "ewm-main-service"
  date_time.format: "yyyy-MM-dd HH:mm:ss"

---
spring:
  config.activate.on-profile: test
  datasource:
    url: jdbc:h2:mem:stats-db
    driver-class-name: org.h2.Driver
    username: statsdb
    password: statsdb
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2.console:
    enabled: true
    path: /ewm-h2-console